kind: pipeline
type: kubernetes
name: test

steps:
- name: english
  image: alpine
  commands:
  - echo hello world

#---
# kind: pipeline
# type: kubernetes
# name: build & test

# steps:

- name: build & push
  image: docker:dind
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
    commands:
      - sleep 5
      - docker build --tag autkast/fanews:d-sha-${DRONE_COMMIT_SHA} .
      - docker push autkast/fanews:d-sha-${DRONE_COMMIT_SHA}

services:
  - name: docker
    image: docker:dind
    privilged: true
    volumes:
    - name: dockersock
      path: /var/run

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock

# ---
# https://vitobotta.com/2019/10/09/ci-cd-with-drone-for-deployment-to-kubernetes-with-helm/
# kind: pipeline
# type: docker
# name: build & test

# trigger:
#   branches:
#     - master
#   event:
#     - push

# steps:
#   - name: restore-cache
#     image: drillster/drone-volume-cache
#     settings:
#       restore: true
#       mount:
#         - target
#     volumes:
#       - name: cache
#         path: /cache

#   - name: prepare-cache
#     image: busybox
#     commands:
#       - mkdir -p /cache/${DRONE_REPO}/target
#       - mkdir -p /cache/${DRONE_REPO}/docker
#     volumes:
#       - name: cache
#         path: /cache
  
#   - name: build
#     image: plugins/docker
#     settings:
#       registry: docker.io
#       repo: docker.io/autkast/fanews
#       tags:
#         - ${DRONE_COMMIT_SHA:0:7}
#         - ${DRONE_COMMIT_BRANCH}
#       force_tag: true
#       use_cache: true
#       # username:
#       #   from_secret: github_registry_username
#       # password:
#       #   from_secret: github_registry_password
#     volumes:
#       - name: docker
#         path: /var/lib/docker

#   - name: rebuild-cache
#     image: drillster/drone-volume-cache
#     settings:
#       rebuild: true
#       mount:
#         - target
#     volumes:
#       - name: cache
#         path: /cache

# volumes:
# - name: cache
#   host:
#     path: /var/cache
# - name: target
#   host:
#     path: /var/cache/${DRONE_REPO}/target
# - name: docker
#   host:
#     path: /var/cache/${DRONE_REPO}/docker