kind: pipeline
type: kubernetes
name: test

steps:
- name: english
  image: alpine
  commands:
  - echo hello world

- name: publish
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: autkast/fanews
    debug: true
    tags:
    - latest

