kind: pipeline
type: kubernetes
name: test

steps:

- name: english
  image: alpine
  commands:
  - echo hello world

- name: publish
  image: plugins/docker
  when:
    branch:
      - master
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: autkast/fanews
    tags:
    - latest
    - sha-${DRONE_COMMIT_SHA}

- name: trigger a test script
  image: bitnami/git
  # when:
  #   branch:
  #     - master
  commands:
    - cd test/
    - sh ./test_script.sh 60
